name: Deploy Web Portfolio
run-name: ${{ github.actor }} is deploying the web portfolio to production 🚀
on:
  push:
    branches:
      - main

jobs:
  deploy-frontend:
    uses: ./.github/workflows/deployNextJs.yml
    secrets: inherit